apiVersion: v1
data:
  config.yaml: "log:\r\n  level: debug\r\n  outputPaths:\r\n    - stdout\r\n\r\nproxy:\r\n
      \ enabled: {{ .Values.proxy.enabled }}\r\n  url: http-server-{{ .Values.proxy.name }}.{{ .Release.Namespace }}.svc.cluster.local\r\n  port: 80\r\n
      \ protocol: http\r\n\r\nservice:\r\n  name: {{ .Values.service.name }}r\n\r\njaeger:\r\n  enabled:
    {{ .Values.jaeger.enabled }}\r\n  endpointUrl: {{ .Values.jaeger.endpointUrl }}"
kind: ConfigMap
metadata:
  name: http-server-config-{{ .Values.config.name }}